services:
  sharedtodolists.api:
    image: sharedtodolists.api
    build:
      context: .
      dockerfile: SharedTodoLists.Api/Dockerfile

  sharedtodolists.application:
    image: sharedtodolists.application
    build:
      context: .
      dockerfile: SharedTodoLists.Application/Dockerfile

